[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cp_amm = "6YeQp4m2Ka2bVn6qxbyFVTRKp2maLWYuuNuposZrqbc2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
